tasks:
  - init: echo "Starter Botpress Server Docker Compose Community" 
    command: docker compose -f examples/docker-compose/docker-compose-community.yaml up 
ports:
    - name: botpress-server
      port: 3000
      onOpen: open-browser
      visibility: public 
    - name: botpress-server-lang
      port: 3100
      onOpen: open-preview
      visibility: public 