tasks:
  - init: echo "Starter Botpress Server Docker Compose Community" 
    command: docker compose -f examples/docker-compose/docker-compose-community.yaml up 
ports:
    - name: botpress-server
      port: 3000
      onOpen: open-preview
      visibility: public 
    - name: botpress-server-lang
      port: 3100
      onOpen: ignore
      visibility: public 
    - name: botpress-server-postgres
      port: 5436
      onOpen: ignore
      visibility: public          
    - name: botpress-server-duck
      port: 8000
      onOpen: ignore
      visibility: public       