apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: botpress-workspace
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
---
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  labels:
    app.kubernetes.io/instance: botpress-server
    app.kubernetes.io/name: botpress-server
    app.openshift.io/runtime: nodejs
    app.openshift.io/runtime-version: '12.18'
    operator.tekton.dev/operand-name: openshift-pipelines-addons
    pipeline.openshift.io/strategy: docker
    pipeline.openshift.io/type: kubernetes
  name: botpress-server
spec:
  params:
    - default: botpress-server
      name: APP_NAME
      type: string
    - default: 'https://github.com/maximilianoPizarro/botpress-server-v12.git'
      name: GIT_REPO
      type: string
    - default: master
      name: GIT_REVISION
      type: string
    - default: >-
        image-registry.openshift-image-registry.svc:5000/mpizarro-dev/botpress-server
      name: IMAGE_NAME
      type: string
    - default: .
      name: PATH_CONTEXT
      type: string
    - default: botpress-server-mpizarro-dev.apps.sandbox-m2.ll9k.p1.openshiftapps.com
      name: EXTERNAL_URL
      type: string
  tasks:
    - name: fetch-repository
      params:
        - name: url
          value: $(params.GIT_REPO)
        - name: revision
          value: $(params.GIT_REVISION)
        - name: subdirectory
          value: ''
        - name: deleteExisting
          value: 'true'
        - name: sslVerify
          value: 'false'
        - name: submodules
          value: 'false'
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: workspace
    - name: build
      params:
        - name: IMAGE
          value: $(params.IMAGE_NAME)
        - name: TLSVERIFY
          value: 'false'
        - name: CONTEXT
          value: $(params.PATH_CONTEXT)
      runAfter:
        - oc-apply-manifest
      taskRef:
        kind: ClusterTask
        name: buildah
      workspaces:
        - name: source
          workspace: workspace
    - name: deploy
      params:
        - name: SCRIPT
          value: oc rollout status deploy/$(params.APP_NAME)
      runAfter:
        - build
      taskRef:
        kind: ClusterTask
        name: openshift-client
    - name: oc-apply-manifest
      params:
        - name: SCRIPT
          value: >-
            oc process k8s/overlay/develop/deployment-patches.yaml -p
            EXTERNAL_URL=$(params.EXTERNAL_URL)


            oc apply -k k8s/overlay/develop 
        - name: VERSION
          value: latest
      runAfter:
        - yq-patches
      taskRef:
        kind: ClusterTask
        name: openshift-client
      workspaces:
        - name: manifest-dir
          workspace: workspace
    - name: yq-patches
      params:
        - name: SCRIPT
          value: >+
            echo "patch external url"


            yq e -i '.spec.template.spec.containers[0].env.[1].value =
            "https://$(params.EXTERNAL_URL)"'
            k8s/overlay/develop/deployment-patches.yaml


            echo "patch image"


            yq e -i '.spec.template.spec.containers[0].image =
            "$(params.IMAGE_NAME)"' k8s/overlay/develop/deployment-patches.yaml


            cat k8s/overlay/develop/deployment-patches.yaml


            echo "patch host"


            yq e -i '.spec.template.spec.containers[0].image =
            "$(params.EXTERNAL_URL)"' k8s/overlay/develop/route.yaml


            cat k8s/overlay/develop/route.yaml

        - name: image
          value: >-
            docker.io/mikefarah/yq:4.27.5@sha256:2be3626ed633fbe1fc33ee9343a1256a6be53334412b2251b9a859f8c145bb53
        - name: files
          value: []
        - name: expression
          value: ''
      runAfter:
        - fetch-repository
      taskRef:
        kind: Task
        name: yq
      workspaces:
        - name: source
          workspace: workspace
  workspaces:
    - name: workspace
