version: "3"

services:
  botpress:
    build:
      context: ./botpress
      dockerfile: Dockerfile
    image: botpress/server
    container_name: botpress-server
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL=postgres://postgres:secretpw@postgres:5435/botpress_db
      - BP_MODULE_NLU_DUCKLINGURL=https://8000-${GITPOD_WORKSPACE_ID}.${GITPOD_WORKSPACE_CLUSTER_HOST}
      - BP_MODULE_NLU_LANGUAGESOURCES=[{"endpoint":"https://3100-${GITPOD_WORKSPACE_ID}.${GITPOD_WORKSPACE_CLUSTER_HOST}"}]
      - EXTERNAL_URL=https://3000-${GITPOD_WORKSPACE_ID}.${GITPOD_WORKSPACE_CLUSTER_HOST} 
      - GITPOD_WORKSPACE_ID=${GITPOD_WORKSPACE_ID}
      - GITPOD_WORKSPACE_CLUSTER_HOST=${GITPOD_WORKSPACE_CLUSTER_HOST}
    depends_on:
      - postgres
    volumes:
      - botpress:/botpress/data

  botpress_lang:
    build:
      context: ./botpress
      dockerfile: Dockerfile
    image: botpress/server
    container_name: botpress-lang
    command: bash -c "./duckling -p 8000 & ./bp lang --langDir /botpress/lang --port 3100"
    ports:
      - 3100:3100    
      - 8000:8000          
    expose:
      - 3100
      - 8000
    volumes:
      - botpress:/botpress/lang

  postgres:
    image: postgres:11.2-alpine
    ports:
      - 5435:5435
    container_name: postgres
    environment:
      PGPORT: 5435
      POSTGRES_DB: botpress_db
      POSTGRES_PASSWORD: secretpw
      POSTGRES_USER: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
  botpress: